name: Autobahn

on:
  [pull_request, push]

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - "5.1"
        allow-prerelease-opam:
          - true
        opam-repositories:
          - |-
            default: https://github.com/ocaml/opam-repository.git
        # include:
        #   - os: windows-latest
        #     ocaml-compiler: ocaml-variants.5.1.0+options,ocaml-option-mingw
        #     allow-prerelease-opam: false
        #     opam-repositories: |-
        #       windows-5.0: https://github.com/dra27/opam-repository.git#windows-5.0
        #       sunset: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
        #       default: https://github.com/ocaml/opam-repository.git

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: test/autobahn/Dockerfile
          push: true
          tags: francoganga/test_server:latest

