name: Autobahn

on:
  [pull_request, push]

permissions: read-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: test/autobahn/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test:
    runs-on: ubuntu-latest
    services:
      test_server:
        image: ghcr.io/francoganga/nomad:autobahn_ci
        ports:
          - 2112:2112
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    container:
      image: crossbario/autobahn-testsuite
      volumes:
        - "${PWD}/test/autobahn/fuzzingclient.json:/fuzzingclient.json"
        - "${PWD}/_build/reports:/reports" 

