name: Run h2spec

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  h2spec:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
        ocaml-compiler:
          - "5.1"
        allow-prerelease-opam:
          - true
        opam-repositories:
          - |-
            default: https://github.com/ocaml/opam-repository.git
        # include:
        #   - os: windows-latest
        #     ocaml-compiler: ocaml-variants.5.1.0+options,ocaml-option-mingw
        #     allow-prerelease-opam: false
        #     opam-repositories: |-
        #       windows-5.0: https://github.com/dra27/opam-repository.git#windows-5.0
        #       sunset: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
        #       default: https://github.com/ocaml/opam-repository.git

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        allow-prerelease-opam: ${{ matrix.allow-prerelease-opam }}
        opam-repositories: ${{ matrix.opam-repositories }}

    - run: opam install . --deps-only --with-test

    - run: opam exec -- dune build --release

    - name: Run h2spec test
      run: opam exec -- dune exec ./test/h2spec.exe
